backend/src/app.module.ts, backend/src/auth/service/auth.service.ts, backend/src/chat/chat.controller.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.module.ts, backend/src/chat/chat.service.ts, backend/src/chat/dto/chat.dto.ts, backend/src/chat/entity/AdminUser.entity.ts, backend/src/chat/entity/BannedUser.entity.ts, backend/src/chat/entity/JoinedDmUser.entity.ts, backend/src/chat/entity/JoinedUser.entity.ts, backend/src/chat/entity/MutedUser.entity.ts, backend/src/chat/entity/chatRoom.entity.ts, backend/src/chat/entity/chatRoomDm.entity.ts, backend/src/user/entity/user.entity.ts, backend/src/user/enum/status.enum.ts
socketio 기능 개발
socket api 정보 및 postman 테스트 qa
https://secret-jackal-406.notion.site/team-transcdence-7cde6bb436ff4398807157fbbc1e079c
=> [backend] add socket module

backend/src/main.ts, backend/src/user/service/user.service.ts, backend/src/user/user.controller.ts
fakeuser 생성 url 입니다.
http://localhost:3000/user/test/create/fakeuser
fakeuser 삭제 url 입니다.
http://localhost:3000/user/test/delete/fakeuser
클라에서 서버로 소켓요청 보낼때 
db에 만들어진 특정 fakeuser token 입력 및 요청하면
응답 받을 수 있을 것 같습니다.
=> [backend] frontend에서 소켓요청 테스트 위한 fakeuser생성 테스트 api추가

backend/src/app.module.ts, backend/src/game/dto/game.dto.ts, backend/src/game/enum/game.enum.ts, backend/src/game/game.controller.ts, backend/src/game/game.gateway.ts, backend/src/game/game.module.ts, backend/src/game/game.service.ts, backend/src/main.ts, backend/src/user/enum/status.enum.ts, backend/src/user/service/match.service.ts, backend/src/user/user.controller.ts
=> add backend game module

backend/src/user/service/block.service.ts, backend/src/user/service/friend.service.ts
- 블락 유저 추가시 중복 입력시 예외처리 코드 추가
- 친구 유저 추가시 중복 입력시 예외처리 코드 추가
- 친구를 블락하지 못하도록 예외처리 코드 추가
=> backend block, friend add duplicate 문제 코드 수정

backend/src/auth/auth.controller.ts, backend/src/chat/chat.gateway.ts, backend/src/game/game.gateway.ts, backend/src/user/enum/status.enum.ts
- userStatus
- OFFLINE,
- ONLINE               - OTP 로그인 후
- CHATCHANNEL  - chat socket 연결 , chat room 입장 후 채널로 나온 상태 , chat room에서 ban 당한 상태
- CHATROOM        - chat room 입장
- GAMECHANNE   - game socket 연결, game room 입장 후 채널로 나온 상태
- GAMEROOM       - game room 입장
=> backend userStatus 수정

frontend/pages/index.tsx, frontend/src/components/CustomButton.tsx
=> Style: LandingPage 버튼 포지셔닝 & xl Button 제작

frontend/pages/game/index.tsx
서버에서 게임 상황 받아와서 win lose 판단 + 게임 set 하는 로직 구현 필요 
현재는 페이지 최하단에 설정 버튼으로 구현되어있음
=> feat: 게임 결과창 win | lose 모달로 표시기능 구현

frontend/pages/auth/login/otp.tsx, frontend/src/components/OtpWindow.tsx
=> feat: Otp 더미 페이지 초안 완성

frontend/pages/chat/index.tsx
현재 제목과 패스워드만 콘솔에 입력 하는 단계 까지만 구현되어 있음
추후에 데이터를 직접 백엔드에 넘겨서 방을 생성하는 기능 구현 필요
=> feat: 채팅방 생성 모달 초안 구현

frontend/src/components/OtpWindow.tsx
커서가 깜빡 거리는것을 안보이게 하고 싶지만 일단 방법 못찾음
=> feat:OTP 입력 실패시 오류표시후 입력칸 초기화

frontend/pages/auth/basic/id.tsx, frontend/pages/fakeLogin.tsx, frontend/pages/index.tsx
백엔드 프론트엔드 유저 데이터 json형식 통일 필요 아니면 맞춰서 넣는 다른 로직 추가 필요
=> feat : 시작 페이지에서 버튼으로 페이크 유저 로그인 기능 구현

frontend/package.json, frontend/pages/chat/[roomNo].tsx
1 접속중인 유저 리스트 받아오면 수정해야함
2 메세지 로그 받아오고 출력하는 기능 구현필요
=> feat:chat/:roomNo 뷰와 로직 일부 구현

frontend/src/components/OptionMenu.tsx, frontend/src/components/RawUserItem.tsx, frontend/src/components/Sidebar.tsx, frontend/src/components/UserItem.tsx, frontend/src/interfaces/RawUserItemProps.ts
친구 추가 버튼 클릭 후 검색 시 왼쪽 마우스로 프로필 접근 가능하고 그 곳에서 친구 추가 가능
=> fix:search시 왼쪽마우스로 프로파일 접근만 허용

frontend/pages/_app.tsx, frontend/pages/chat/[roomNo].tsx, frontend/pages/chat/index.tsx, frontend/pages/fakeLogin.tsx, frontend/pages/game/options.tsx, frontend/pages/index.tsx, frontend/pages/user/[username].tsx, frontend/pages/watch/index.tsx, frontend/src/components/Header.tsx, frontend/src/components/Sidebar.tsx, frontend/src/interfaces/UserProps.ts, frontend/src/stores/userStore.ts
이제 winCnt, loseCnt 뿐만 아니라 useOtp 속성도 UserProps에서 제거하였습니다. 
사실 다른 사람의 useOtp는 개인정보라는 점에서 다른 사람이 볼 수 있으면 안되긴 하죠... ㅎㅎㅎ 
Header에서는 fetchUseOtp 를 별도로 사용하여 나의 useOtp 정보는 연동되도록 하였습니다.
=> !FEAT: UserProps에서 useOtp 속성 제거.

frontend/src/components/Sidebar.tsx
=> fix: 친구추가 창에서 본인이름 안뜨게 수정

frontend/pages/chat/index.tsx, frontend/src/components/Sidebar.tsx, frontend/src/stores/allUserStore.ts
모든 유저 갱신하는 부분에서 alluserstore
사용하고 filter 이용해서 한번 거른뒤 이용하면됨
=> feat: AllUserStore만들고 이를 이용하여 친추추가 목록과 채팅방 대기인원 갱신

frontend/pages/chat/index.tsx, frontend/src/components/RawUserItem.tsx, frontend/src/components/Sidebar.tsx
채팅방 우측 접속 인원 표시 둥글게 변경
ISSUE:
UserItem 고정 크기가 없어서 아이디 글자 수 등의 차이로 인해 
패널 자체의 크기가 변경됨 
-> 변경될 때마다 아바타 표시 위치와 아이디글자 표시 위치가 제각각
-> 현재 userItem 컴포넌트에서 가운데에 스페이서 추가해서 양쪽으로 벌려놓은 상태 +  import 해서 사용시 flex등으로 한번 감싸서 넓이 고정해서 사용하면 해결 가능
=> minor changes

backend/src/chat/chat.service.ts
=> BE findChatRoomAll owner 정보 추가

backend/src/chat/chat.service.ts
-[x] chatRoomById, chatRoomByName, chatRoomDmById 소켓 이벤트 호출시 chatLog 추가 및 토큰 정보 제거
-[x] API 문서 업데이트
=> BE chatLog, chatDmLog 응답시 token 제거

frontend/pages/chat/[roomNo].tsx
채팅 4개씩 나옴
그래도 채팅 을 치면 옆에 방안에 있는 유저 보여지긴함
=> feat:채팅 기능 대충 초본

backend/package.json, backend/src/auth/auth.controller.ts, backend/src/auth/dto/auth.dto.ts, backend/src/auth/security/passport.42auth.strategy.ts, backend/src/auth/service/auth42.service.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.ts, backend/src/chat/dto/chat.dto.ts, backend/src/game/dto/game.dto.ts, backend/src/game/enum/game.enum.ts, backend/src/game/game.gateway.ts, backend/src/game/game.service.ts, backend/src/user/dto/user.dto.ts, backend/src/user/service/block.service.ts, backend/src/user/service/friend.service.ts, backend/src/user/service/user.service.ts, backend/src/user/user.controller.ts
-[x] 요청 데이터 validation , sanitizing 기능추가
-[x] readonly로 service 캡슐화
-[x] class 내 메소드 리턴 유형 명시화
=> BE sanitize data, readonly, return type

frontend/pages/home.tsx, frontend/src/interfaces/GameOptionsProps.ts, frontend/src/interfaces/GamePlayerProps.ts, frontend/src/interfaces/GameRoomProps.ts, frontend/src/stores/gameStore.tsx
Game information And Matching Button
=> Game Information

frontend/pages/chat/index.tsx
=> feat: 비밀번호 넣는 모달과 입력까지 일 단 구현

frontend/src/stores/userStore.ts
바뀐 기준에 따라 api 요청 정보 수정함 
변경전  : customFetch('POST', 'user/friend/name/' + name, { username: name });
변경후 : customFetch('POST', 'user/friend/name', { username: name });
=> fix: add / delete friend api argument fix

frontend/src/components/UserItem.tsx
소켓 연결해서 정보 받아오고 업데이트 하는 부분은 아직 안되어 있음
=> feat: UserItem popover DM 초안

backend/src/auth/auth.controller.ts, backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.ts, backend/src/chat/dto/chat.dto.ts, backend/src/user/user.controller.ts
-[x] updatePwd API 문서 업데이트
-[x] chat parameter validation, sanitization
=> BE chat validation, sanitization

frontend/src/components/UserItem.tsx
=> feat:dm기능 불완전 초안

frontend/pages/chat/index.tsx, frontend/src/stores/chatStore.ts
방법을 몰라서 아직 미완성
비밀번호 틀리면 잠깐 chat/roomNO로 라우팅 됫다가 다시 chat/ 으로 돌아옴..
=> feat:chat Room 비밀번호 판단하는 기능 추가

frontend/pages/chat/index.tsx
기존에 response가 에러인 경우에만 와서 비번맞았을때만 방들어가는 로직에 하자가 있던것 해결 ( 살짝 들어갔다 나오는 식이었음 )
=> fix: 비밀번호 맞았을때만 roomNo로 라우팅 기능 완성

frontend/pages/game/options.tsx, frontend/pages/home.tsx, frontend/src/interfaces/GameOptionsProps.ts, frontend/src/interfaces/GamePlayerProps.ts, frontend/src/interfaces/GameRoomProps.ts, frontend/src/interfaces/GameUserProps.ts, frontend/src/stores/gameStore.tsx
=> Game Ready and Room Setting

frontend/pages/chat/[roomNo].tsx, frontend/src/components/ChatAdminOptionMenu.tsx, frontend/src/stores/chatStore.ts
=> feat : mute User 기능 구현

frontend/pages/chat/[roomNo].tsx, frontend/src/components/ChatAdminOptionMenu.tsx, frontend/src/stores/chatStore.ts
=> feat : remove Friend 초안

frontend/src/components/UserItem.tsx
=> feat : dm 메세지 쌓이는 스택 구현

frontend/pages/game/[roomNo].tsx, frontend/pages/game/options.tsx, frontend/pages/home.tsx, frontend/src/components/MatchInfo.tsx, frontend/src/stores/gameStore.tsx
Socket Making Error and Game Finish proc
=> Check the socket with gameover

backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.ts, backend/src/chat/dto/chat.dto.ts
-[x] api 문서추가
-[x] public -> protected 일때, 초기 비밀번호 값 = "0000" 로 변경
-[x] protected ->public 일때,  비밀번호 = "" 로 변경
-[x] 현재방 status와 입력받은 status 값 같으면 예외발생
-[x]  private 방이거나, private 방으로는 작동 X
*public 에서 protected로 바꾼다면, updateStatus API -> updatePwd API 통해서 원하는 비밀번호로 방 상태와 비번 수정가능
=> BE updateStatus 추가

frontend/src/components/UserItem.tsx
기존에 메시지 스택 lstIndex 저장 로직에 문제점 발견  : 채팅창 켜져있을때는 last Index갱신 안됬었음
수정완료
=> fix : dm 메세지 스택 로직 변경

frontend/src/components/ChatAdminOptionMenu.tsx, frontend/src/components/ChatUserItem.tsx
채팅방에서 owner 가 아니면 어드민->오너 어드민->어드민 에게는 어드민전용메뉴가 나오지 않게 수정
=> fix : 어드민 메뉴 뜨는 조건 수정

frontend/pages/auth/basic/id.tsx, frontend/pages/chat/index.tsx
맨처음 로그인시 아이디 넣는곳
채팅방 생성하는 모달 
비번 채팅방 입장하는 모달
=> feat : 모든 입력창에 enter로 진행 가능하게 수정

frontend/pages/auth/basic/avatar.tsx, frontend/pages/auth/basic/id.tsx, frontend/pages/chat/[roomNo].tsx, frontend/pages/chat/index.tsx
=> feat : 모든 입력창에서 오토포커스 및 엔터로 제출

frontend/src/components/UserItem.tsx, frontend/src/stores/chatStore.ts
chat store내에서 각 dm의 lastIdx를 map 으로 관리하도록 변경
=> feat: 게임끝나고 홈와도 메세지 스택 유지

frontend/pages/_app.tsx, frontend/pages/game/options.tsx, frontend/src/utils/getJwtToken.ts
=> html Event
